// Generates the synthetic fixtures in test-fixtures/prompt-history/ (tbd-02, M5 investigation).
// Run from the repo root:  scripts/run-node .github/tmp/2026-10-05--08-37--answers-reviews-m5/tbd-02-copilot-history/generate-fixtures.ts
// Every text field is an obvious placeholder; the only real strings are the runner's fixed boilerplate markers
// (code-generated by execute-copilot-session, never typed by a human) — the classifier needs them.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve('test-fixtures/prompt-history');
const HOME = path.join(ROOT, 'home');
const SS = path.join(HOME, '.copilot/session-state');
const AH = path.join(HOME, 'Library/Application Support/Code/agentSessionData');
const WS = path.join(HOME, 'Library/Application Support/Code/User/workspaceStorage');
const EW = path.join(HOME, 'Library/Application Support/Code/User/globalStorage/emptyWindowChatSessions');

const T0 = Date.parse('2026-01-11T08:00:00.000Z'); // Sunday 10:00 Asia/Jerusalem (+02:00), day key 2026-01-11
const at = (min: number, sec = 0): number => T0 + min * 60_000 + sec * 1000;
const iso = (ms: number): string => new Date(ms).toISOString();
const localIso = (ms: number): string => new Date(ms + 2 * 3600_000).toISOString().replace('Z', '+02:00');
const sid = (n: number): string => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const ahid = (n: number): string => `a0000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const eid = (s: number, n: number): string => `e${String(s).padStart(7, '0')}-0000-4000-8000-${String(n).padStart(12, '0')}`;
const uuid = (tag: string, n: number): string => `${tag.padEnd(8, '0').slice(0, 8)}-0000-4000-8000-${String(n).padStart(12, '0')}`;

const RUNNER_TAIL =
  'WORKING AGREEMENT: These interaction preferences govern this task, placeholder agreement text.\n' +
  'TASK OUTCOME: A success signal means substantive task completion, placeholder outcome text.';
const OLD_RUNNER_TAIL =
  'placeholder instruction text, the very LAST thing you do MUST be to rename the prompt file `x.vscode.launched-2026-01-11--10-00-00.md` to `x.vscode.completed.md`';

type Json = Record<string, unknown>;
const write = (file: string, text: string): void => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text); };
const jsonl = (rows: Json[], tail = ''): string => rows.map((r) => JSON.stringify(r)).join('\n') + '\n' + tail;

// ---------------------------------------------------------------- CLI / agent store (~/.copilot/session-state)
interface Ev { type: string; data: Json; ts: number; agentId?: string }
function events(s: number, evs: Ev[]): Json[] {
  let parent: string | null = null;
  return evs.map((e, i) => {
    const id = eid(s, i + 1);
    const row: Json = { type: e.type, data: e.data, id, timestamp: iso(e.ts), parentId: parent };
    if (e.agentId) row.agentId = e.agentId;
    parent = id;
    return row;
  });
}
const start = (s: number, ts: number): Ev => ({ type: 'session.start', ts, data: { sessionId: sid(s), version: 1, producer: 'copilot-agent', copilotVersion: '0.0.0', startTime: iso(ts), selectedModel: 'model-x', reasoningEffort: 'high', contextTier: 'long_context', context: { cwd: '/fixture/repo' }, remoteSteerable: false, alreadyInUse: false } });
const hooks = (ts: number): Ev[] => [{ type: 'hook.start', ts, data: { hookType: 'placeholder' } }, { type: 'hook.end', ts, data: { hookType: 'placeholder' } }];
let msgN = 0;
const userMsg = (ts: number, content: string, extra: Json = {}, agentId?: string): Ev => ({
  type: 'user.message', ts, agentId,
  data: { content, transformedContent: `<current_datetime>${localIso(ts)}</current_datetime>\n\n${content}`, attachments: [], messageId: uuid('m', ++msgN), supportedNativeDocumentMimeTypes: [], delivery: 'idle', interactionId: uuid('i', msgN), turnId: '0', parentAgentTaskId: uuid('p', msgN), ...extra },
});
const sysMsg = (ts: number, agentId?: string): Ev => ({ type: 'system.message', ts, agentId, data: { role: 'system', content: 'system prompt placeholder', interactionId: uuid('i', 900) } });
const turn = (ts: number, text: string, agentId?: string): Ev[] => [
  { type: 'assistant.turn_start', ts, agentId, data: { turnId: '1', interactionId: uuid('i', 901) } },
  { type: 'assistant.message', ts, agentId, data: { messageId: uuid('a', 1), content: text, toolRequests: [] } },
  { type: 'assistant.turn_end', ts, agentId, data: { turnId: '1' } },
];
const tool = (ts: number, name: string, callId: string, done: number | null, telemetry: Json = {}, agentId?: string): Ev[] => {
  const out: Ev[] = [{ type: 'tool.execution_start', ts, agentId, data: { toolCallId: callId, toolName: name, arguments: { question: 'question placeholder' } } }];
  if (done !== null) out.push({ type: 'tool.execution_complete', ts: done, agentId, data: { toolCallId: callId, model: 'model-x', interactionId: uuid('i', 902), turnId: '1', success: true, result: { content: 'tool result placeholder' }, toolTelemetry: telemetry } });
  return out;
};
const answered = { properties: { outcome: 'answered', had_choices: true, was_freeform: false }, restrictedProperties: { question: 'question placeholder', choices: 'choices placeholder', answer: 'answer placeholder' } };
const yaml = (s: number, client: string, created: number): string =>
  `id: ${sid(s)}\ncwd: /fixture/repo\ngit_root: /fixture/repo\nbranch: main\nclient_name: ${client}\nname: |-\n  prompt text placeholder (the first prompt is copied here)\n  second line placeholder\nuser_named: false\nsummary_count: 0\nfork_count: 0\ncreated_at: ${iso(created)}\nupdated_at: ${iso(created)}\n`;
function cliSession(s: number, client: string, evs: Ev[], tail = ''): Json[] {
  const rows = events(s, evs);
  write(path.join(SS, sid(s), 'events.jsonl'), jsonl(rows, tail));
  write(path.join(SS, sid(s), 'workspace.yaml'), yaml(s, client, evs[0].ts));
  return rows;
}
const idOf = (rows: Json[], pred: (r: Json) => boolean): string => String(rows.find(pred)?.id);
const msgId = (rows: Json[], content: string, agent = false): string =>
  idOf(rows, (r) => r.type === 'user.message' && (r.data as Json).content === content && (agent ? !!r.agentId : !r.agentId));

// S1 — agent-host session typed by the owner: 2 human prompts, 1 retry, 1 answered ask_user, 1 unanswered ask_user,
// a subagent exchange, a system steering message, and a torn (incomplete) last line.
const SUB = 'b0000000-0000-4000-8000-000000000001';
const s1 = cliSession(1, 'vscode-agent-host', [
  start(1, at(0)), { type: 'session.permissions_changed', ts: at(0), data: { mode: 'placeholder' } },
  ...hooks(at(0, 1)), userMsg(at(0, 2), 'prompt text 1'), sysMsg(at(0, 2)),
  ...turn(at(0, 10), 'assistant text placeholder'),
  ...tool(at(1), 'bash', 'call-s1-bash', at(1, 5), {}),
  ...tool(at(2), 'ask_user', 'call-s1-ask1', at(3), answered),
  ...turn(at(3, 5), 'assistant text placeholder'),
  userMsg(at(10), 'prompt text 2'),
  { type: 'subagent.started', ts: at(10, 30), agentId: SUB, data: { toolCallId: 'call-s1-task', agentName: 'explore', agentDisplayName: 'placeholder-agent', agentDescription: 'description placeholder', model: 'model-x', agentType: 'explore', executionMode: 'background' } },
  sysMsg(at(10, 31), SUB), userMsg(at(10, 31), 'subagent prompt text 1', { source: `agent-${sid(1)}` }, SUB),
  ...turn(at(10, 40), 'subagent text placeholder', SUB),
  { type: 'subagent.completed', ts: at(11), agentId: SUB, data: { toolCallId: 'call-s1-task', agentName: 'explore' } },
  userMsg(at(12), 'prompt text 2'), // same text again within 15 min: a retry -> unclassified
  userMsg(at(13), '', { source: 'system', delivery: 'steering', attachments: undefined, parentAgentTaskId: undefined }),
  ...tool(at(14), 'ask_user', 'call-s1-ask2', null), // never answered (session ended)
], '{"type":"assistant.message","data":{"content":"torn line placehol');

// S2 — launched by execute-copilot-session (runner markers, bare-UUID turn), later a typed message (request_ turn),
// and an ask_user the owner answered.
const s2 = cliSession(2, 'vscode-agent-host', [
  start(2, at(20)), ...hooks(at(20)), userMsg(at(20, 1), `prompt text 3 (task file placeholder)\n${RUNNER_TAIL}`), sysMsg(at(20, 1)),
  ...turn(at(20, 30), 'assistant text placeholder'),
  ...tool(at(21), 'ask_user', 'call-s2-ask1', at(24), answered),
  ...turn(at(24, 5), 'assistant text placeholder'),
  userMsg(at(30), 'prompt text 4'),
]);

// S3 — runner session, fully automated (one runner message, nothing else human).
const s3 = cliSession(3, 'vscode-agent-host', [start(3, at(40)), userMsg(at(40, 1), `prompt text 5 (task file placeholder)\n${RUNNER_TAIL}`), ...turn(at(41), 'assistant text placeholder')]);

// S4 — another AHP client (bare-UUID turns) without runner markers: automated.
const s4 = cliSession(4, 'vscode-agent-host', [start(4, at(50)), userMsg(at(50, 1), 'prompt text 6'), ...turn(at(51), 'x'), userMsg(at(56), 'prompt text 7'), ...turn(at(57), 'x')]);

// S5 — headless `copilot -p` tool call (client github/cli): unclassified.
cliSession(5, 'github/cli', [start(5, at(60)), userMsg(at(60, 1), 'prompt text 8'), sysMsg(at(60, 1)), ...turn(at(60, 5), 'x'), { type: 'session.shutdown', ts: at(60, 6), data: { shutdownType: 'routine' } }]);

// S6 — S1's first part copied into a new session (client vscode, "continue in VS Code"): same event ids and
// timestamps for the copied lines (dedupe!), then one new typed prompt (no turn index -> human, medium confidence).
{
  const copied = s1.slice(0, 13); // session.start .. ask1 complete
  const own = events(6, [{ type: 'session.resume', ts: at(70), data: { resumeTime: iso(at(70)), eventsFileSizeBytes: 0, eventCount: copied.length } }, userMsg(at(70, 5), 'prompt text 9'), ...turn(at(71), 'x')]);
  const rows = [{ ...copied[0], data: { ...(copied[0].data as Json), sessionId: sid(6) } }, ...copied.slice(1), ...own];
  write(path.join(SS, sid(6), 'events.jsonl'), jsonl(rows));
  write(path.join(SS, sid(6), 'workspace.yaml'), yaml(6, 'vscode', at(70)));
}

// S7 — JetBrains session launched by the runner (markers), a later typed message (no turn index: needs `interactive`
// corroboration), and CLI form-elicitation variants of ask_user (accept = answer; cancel = unclassified).
cliSession(7, 'copilot-intellij', [
  start(7, at(80)), userMsg(at(80, 1), `prompt text 10 (task file placeholder)\n${RUNNER_TAIL}`), ...turn(at(80, 30), 'x'),
  ...tool(at(81), 'ask_user', 'call-s7-ask1', at(82), { properties: { elicitation_action: 'accept', elicitation_field_types: 'string' }, metrics: { elicitation_field_count: 1 } }),
  ...tool(at(83), 'ask_user', 'call-s7-ask2', at(85), { properties: { elicitation_action: 'cancel', elicitation_field_types: 'string' }, metrics: { elicitation_field_count: 1 } }),
  userMsg(at(90), 'prompt text 11'), ...turn(at(91), 'x'),
]);

// S8 — agent-host session whose turn row never appears in agentSessionData: unclassified after the deferral window.
const s8 = cliSession(8, 'vscode-agent-host', [start(8, at(100)), userMsg(at(100, 1), 'prompt text 12'), ...turn(at(101), 'x')]);

// ---------------------------------------------------------------- agent-host turn index (agentSessionData/<ahId>/session.db)
// Shipped as SQL (materialise with node:sqlite: new DatabaseSync(dbPath).exec(sql)). Real schema subset.
const q = (v: string): string => `'${v.replace(/'/g, "''")}'`;
function ahDb(dir: string, meta: Record<string, string>, turns: [string, string | null][]): void {
  const sql = [
    'CREATE TABLE session_metadata (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL);',
    'CREATE TABLE turns (id TEXT PRIMARY KEY NOT NULL, event_id TEXT, checkpoint_ref TEXT);',
    'CREATE INDEX idx_turns_event_id ON turns(event_id);',
    ...Object.entries(meta).map(([k, v]) => `INSERT INTO session_metadata VALUES (${q(k)}, ${q(v)});`),
    ...turns.map(([id, ev]) => `INSERT INTO turns VALUES (${q(id)}, ${ev === null ? 'NULL' : q(ev)}, NULL);`),
  ].join('\n') + '\n';
  write(path.join(AH, dir, 'session.sql'), sql);
}
const provider = (s: number): string => JSON.stringify({ sdkSessionId: sid(s), model: { id: 'model-x', config: { thinkingLevel: 'high' } } });
const ui = { configValues: JSON.stringify({ autoApprove: 'default', mode: 'interactive', isolation: 'folder', branch: 'main' }), customTitleSource: 'auto', titleGenerationStrategy: 'deferred', peerChats: '[]' };
const runner = { configValues: JSON.stringify({ autoApprove: 'autoApprove', mode: 'interactive', isolation: 'folder', branch: 'origin/main' }), customTitleSource: 'user', titleGenerationStrategy: 'deferred', peerChats: '[]' };
ahDb(ahid(1), { defaultChatProviderData: provider(1), ...ui }, [
  [`request_${uuid('r1', 1)}`, msgId(s1, 'prompt text 1')],
  [`request_${uuid('r1', 2)}`, idOf(s1, (r) => r.type === 'user.message' && (r.data as Json).content === 'prompt text 2' && !r.agentId)],
  [`request_${uuid('r1', 3)}`, String(s1.filter((r) => r.type === 'user.message' && (r.data as Json).content === 'prompt text 2' && !r.agentId)[1].id)],
  [`request_${uuid('r1', 4)}`, null], // a UI turn that never produced a user.message (e.g. aborted at once)
]);
// A chat-backing db of the same SDK session, no turns: readers must MERGE per sdkSessionId, not overwrite.
ahDb(`default-${Buffer.from(`copilotcli:/${ahid(1)}`).toString('base64')}`, { 'agentHost.chatProviderData': provider(1) }, []);
ahDb(ahid(2), { defaultChatProviderData: provider(2), ...runner }, [
  [uuid('t2', 1), String(s2.find((r) => r.type === 'user.message')?.id)],
  [`request_${uuid('r2', 1)}`, msgId(s2, 'prompt text 4')],
]);
ahDb(ahid(3), { defaultChatProviderData: provider(3), ...runner }, [[uuid('t3', 1), String(s3.find((r) => r.type === 'user.message')?.id)]]);
ahDb(ahid(4), { defaultChatProviderData: provider(4), ...runner }, [
  [uuid('t4', 1), msgId(s4, 'prompt text 6')], [uuid('t4', 2), msgId(s4, 'prompt text 7')],
]);
ahDb(ahid(8), { defaultChatProviderData: provider(8), ...ui }, []);
void s8;

// ---------------------------------------------------------------- VS Code native op-logs
// kind 0 = initial snapshot, 1 = set at k, 2 = push at k (with i: truncate to i first; no v: pure truncate), 3 = delete.
const req = (n: number, ts: number, text: string, extra: Json = {}): Json => ({
  requestId: `request_${uuid('v', n)}`, timestamp: ts, agent: { id: 'github.copilot.editsAgent' }, modelId: 'model-x', hiddenFromTranscript: false,
  responseId: `response_${uuid('w', n)}`, modelState: { value: 0 }, contentReferences: [], codeCitations: [], timeSpentWaiting: 0,
  modeInfo: { kind: 'agent', isBuiltin: true, telemetryModeId: 'agent', telemetryModeName: 'agent', permissionLevel: 'default' },
  response: [{ value: 'response text placeholder', supportThemeIcons: false }], message: { text, parts: [{ kind: 'text', text }] },
  variableData: { variables: [] }, ...extra,
});
const carousel = (resolveId: string, answer: boolean): Json => ({
  kind: 'questionCarousel', resolveId, allowSkip: true,
  questions: [{ id: `${resolveId}:0`, type: 'singleSelect', title: 'title placeholder', message: 'question placeholder', options: [{ id: 'o1', label: 'option placeholder', value: 'option placeholder' }], allowFreeformInput: true }],
  ...(answer ? { isUsed: true, data: { [`${resolveId}:0`]: { selectedValue: 'answer placeholder' } } } : {}),
});
const askTool = (callId: string): Json => ({ kind: 'toolInvocationSerialized', toolId: 'vscode_askQuestions', toolCallId: callId, invocationMessage: { value: 'placeholder' }, isComplete: false, source: { type: 'internal', label: 'placeholder' } });
const root = (id: string, requests: Json[]): Json => ({ version: 3, creationDate: at(0), customTitle: 'title placeholder', initialLocation: 'panel', responderUsername: 'GitHub Copilot', sessionId: id, hasPendingEdits: false, requests, pendingRequests: [], inputState: { attachments: [], inputText: '', permissionLevel: 'default' } });

const V1 = uuid('vs', 1);
const v1Q1 = req(1, at(110), 'prompt text 21');
const v1Q2 = req(2, at(115), 'prompt text 22');
const v1Q3 = req(3, at(118), 'system initiated text placeholder', { isSystemInitiated: true, systemInitiatedLabel: 'label placeholder', terminalExecutionId: 'term-1' });
const v1Q2retry = req(4, at(119), 'prompt text 22');
const v1Q5 = req(5, at(125), 'prompt text 23');
const v1Lines: Json[] = [
  { kind: 0, v: root(V1, [v1Q1]) },
  { kind: 1, k: ['inputState', 'inputText'], v: 'typing placeholder' },
  { kind: 2, k: ['requests', 0, 'response'], v: [askTool('call-v1-q1'), carousel('call-v1-q1', false)] },
  { kind: 2, k: ['requests', 0, 'response'], v: [askTool('call-v1-q1'), carousel('call-v1-q1', true), { value: 'response text placeholder' }], i: 1 },
  { kind: 1, k: ['requests', 0, 'result'], v: { timings: { firstProgress: 1000, totalElapsed: 5000 } } },
  { kind: 2, k: ['requests'], v: [v1Q2] },
  { kind: 2, k: ['requests'], v: [v1Q3] },
  { kind: 2, k: ['requests'], v: [v1Q2retry], i: 1 }, // retry: Q2 (+Q3) removed, same text, new id -> unclassified
  { kind: 2, k: ['requests'], i: 1 },                 // pure truncate (no v)
  { kind: 2, k: ['requests'], v: [v1Q5], i: 1 },      // edited and resent: new text -> human
  { kind: 3, k: ['inputState', 'inputText'] },
  { kind: 1, k: ['requests', 1, 'completionTokens'], v: 100 },
];
write(path.join(WS, 'fixturehash0001/workspace.json'), JSON.stringify({ folder: 'file:///fixture/repo' }, null, 2) + '\n');
write(path.join(WS, 'fixturehash0001/chatSessions', `${V1}.jsonl`), jsonl(v1Lines));

// V2 — old-style runner launch (marker from a pre-2026-09-09 runner) followed by a human request.
const V2 = uuid('vs', 2);
write(path.join(WS, 'fixturehash0001/chatSessions', `${V2}.jsonl`), jsonl([
  { kind: 0, v: root(V2, []) },
  { kind: 2, k: ['requests'], v: [req(11, at(130), `prompt text 24 (task file placeholder)\n${OLD_RUNNER_TAIL}`)] },
  { kind: 2, k: ['requests'], v: [req(12, at(135), 'prompt text 25')] },
]));

// V3 — empty-window chat (globalStorage/emptyWindowChatSessions): one human request.
const V3 = uuid('vs', 3);
write(path.join(EW, `${V3}.jsonl`), jsonl([{ kind: 0, v: root(V3, [req(21, at(140), 'prompt text 26')]) }]));

// Compaction variant of V1: VS Code rewrote the whole file as one kind:0 snapshot (after > 512 entries).
// Re-reading it after V1 must yield nothing new (same requestIds / resolveIds).
const v1Final = [{ ...v1Q1, response: [askTool('call-v1-q1'), carousel('call-v1-q1', true), { value: 'response text placeholder' }] }, v1Q5];
write(path.join(ROOT, 'variants/compacted/Library/Application Support/Code/User/workspaceStorage/fixturehash0001/chatSessions', `${V1}.jsonl`), jsonl([{ kind: 0, v: root(V1, v1Final) }]));

console.log('fixtures written under', path.relative(process.cwd(), ROOT));
